coding_task:
  description: >
    Develop Python code to complete this assignment: {assignment}.
    First outline the approach, then write clean, efficient code,
    and run it to capture the results.
  expected_output: >
    A text file containing the well-documented Python code
    followed by the actual program output.
  agent: coder
  output_file: output/code_and_output.txt