propose:
  description: >
    Present a strong, persuasive argument in favor of the motion: {motion}. 
    Keep it clear, logical, and convincing.
  expected_output: >
    A concise, well-structured argument supporting the motion: {motion}.
  agent: debater
  output_file: output/propose.md

oppose:
  description: >
    Present a strong, persuasive argument opposing the motion: {motion}. 
    Keep it clear, logical, and convincing.
  expected_output: >
    A concise, well-structured argument against the motion: {motion}.
  agent: debater
  output_file: output/oppose.md

decide:
  description: >
    Review both arguments on the motion: {motion} and determine which side 
    is more persuasive, based solely on the merits of the arguments.
  expected_output: >
    A clear verdict naming the winner (Propose or Oppose), along with 
    2–3 sentences explaining why that side was more convincing.
  agent: judge
  output_file: output/decide.md